[mqttms.mqtt]
host = "broker.emqx.io"
port = 1883
username = ""
password = ""
client_id = "client_394578"
timeout = 30.0
long_payload = 25

[mqttms.ms]
client_mac = "1234567890A3"
server_mac = "F412FACEF2E8"     # ESP32 module: "F412FAD56AF4"
cmd_topic = "@/server_mac/CMD/format"
rsp_topic = "@/client_mac/RSP/format"
timeout = 5.0

[logging]
verbose = false

[dut]
ident = "109380"
name = "Smart Ventilator"
serial_date = "2501"
serialn = "0000001"
serial_separator = "-"

[tests]
motoron = 3.0
motoroff = 1.0

[options]
snonly = false
#dutdelay = 4.0
interactive = true
#nopairing = false